"""Measure live API concurrency, latency percentiles, and error rate."""

from __future__ import annotations

import argparse
import asyncio
from collections import Counter
from datetime import datetime
import hashlib
import hmac
import json
import math
import os
from pathlib import Path
import statistics
import time
from typing import Any

import httpx


BACKEND_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = BACKEND_ROOT / "evaluation" / "results"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run a bounded API concurrency test.")
    parser.add_argument("target", choices=("health", "repository", "webhook", "assistant"))
    parser.add_argument("--base-url", default="http://127.0.0.1:8000")
    parser.add_argument("--owner")
    parser.add_argument("--name")
    parser.add_argument("--question", default="这个项目的核心架构是什么？")
    parser.add_argument("--requests", type=int, default=50)
    parser.add_argument("--concurrency", type=int, default=10)
    parser.add_argument("--timeout", type=float, default=90.0)
    parser.add_argument("--webhook-secret", default=os.getenv("GITHUB_WEBHOOK_SECRET"))
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT)
    return parser.parse_args()


def percentile(values: list[float], quantile: float) -> float:
    ordered = sorted(values)
    index = max(0, math.ceil(len(ordered) * quantile) - 1)
    return ordered[index]


def webhook_request(index: int, secret: str | None) -> tuple[str, str, bytes | None, dict[str, str]]:
    payload = {
        "action": "opened",
        "issue": {
            "number": 900000 + index,
            "title": f"Load test issue {index}",
            "body": "Generated by the bounded IssueScope load test.",
            "state": "open",
            "html_url": f"https://github.com/load-test/repo/issues/{900000 + index}",
            "user": {"login": "load-test"},
            "labels": [],
            "comments": 0,
        },
        "repository": {"full_name": "load-test/repo"},
    }
    body = json.dumps(payload, separators=(",", ":")).encode("utf-8")
    headers = {
        "Content-Type": "application/json",
        "X-GitHub-Event": "issues",
        "X-GitHub-Delivery": f"load-{time.time_ns()}-{index}",
    }
    if secret:
        digest = hmac.new(secret.encode("utf-8"), body, hashlib.sha256).hexdigest()
        headers["X-Hub-Signature-256"] = f"sha256={digest}"
    return "POST", "/api/webhooks/github", body, headers


def build_request(args: argparse.Namespace, index: int) -> tuple[str, str, bytes | None, dict[str, str]]:
    if args.target == "health":
        return "GET", "/api/health", None, {}
    if args.target == "repository":
        return "GET", f"/api/repositories/{args.owner}/{args.name}", None, {}
    if args.target == "webhook":
        return webhook_request(index, args.webhook_secret)

    body = json.dumps({
        "owner": args.owner,
        "name": args.name,
        "message": args.question,
        "freshness": "cache_first",
        "history": [],
    }, ensure_ascii=False).encode("utf-8")
    return "POST", "/api/assistant/chat", body, {"Content-Type": "application/json"}


async def execute_one(
    client: httpx.AsyncClient,
    args: argparse.Namespace,
    index: int,
) -> dict[str, Any]:
    method, path, body, headers = build_request(args, index)
    started = time.perf_counter()
    try:
        response = await client.request(method, path, content=body, headers=headers)
        return {
            "index": index,
            "status_code": response.status_code,
            "success": response.is_success,
            "latency_ms": round((time.perf_counter() - started) * 1000, 2),
            "error": None if response.is_success else response.text[:300],
        }
    except httpx.HTTPError as exc:
        return {
            "index": index,
            "status_code": None,
            "success": False,
            "latency_ms": round((time.perf_counter() - started) * 1000, 2),
            "error": str(exc),
        }


async def run_load(args: argparse.Namespace) -> tuple[list[dict[str, Any]], float]:
    queue: asyncio.Queue[int] = asyncio.Queue()
    for index in range(args.requests):
        queue.put_nowait(index)

    results: list[dict[str, Any]] = []
    limits = httpx.Limits(
        max_connections=args.concurrency,
        max_keepalive_connections=args.concurrency,
    )
    async with httpx.AsyncClient(
        base_url=args.base_url.rstrip("/"),
        timeout=args.timeout,
        limits=limits,
    ) as client:
        async def worker() -> None:
            while True:
                try:
                    index = queue.get_nowait()
                except asyncio.QueueEmpty:
                    return
                try:
                    results.append(await execute_one(client, args, index))
                finally:
                    queue.task_done()

        started = time.perf_counter()
        await asyncio.gather(*(worker() for _ in range(args.concurrency)))
        elapsed = time.perf_counter() - started
    return sorted(results, key=lambda result: result["index"]), elapsed


def summarize(args: argparse.Namespace, results: list[dict[str, Any]], elapsed: float) -> dict[str, Any]:
    latencies = [float(result["latency_ms"]) for result in results]
    successful = sum(bool(result["success"]) for result in results)
    statuses = Counter(str(result["status_code"] or "network_error") for result in results)
    return {
        "target": args.target,
        "base_url": args.base_url,
        "requests": len(results),
        "concurrency": args.concurrency,
        "successful": successful,
        "failed": len(results) - successful,
        "success_rate_percent": round(successful * 100 / len(results), 2),
        "wall_time_seconds": round(elapsed, 3),
        "throughput_requests_per_second": round(len(results) / elapsed, 2),
        "latency_ms": {
            "average": round(statistics.fmean(latencies), 2),
            "p50": round(percentile(latencies, 0.5), 2),
            "p95": round(percentile(latencies, 0.95), 2),
            "p99": round(percentile(latencies, 0.99), 2),
            "maximum": round(max(latencies), 2),
        },
        "status_counts": dict(statuses),
    }


def markdown_report(summary: dict[str, Any], generated_at: str) -> str:
    latency = summary["latency_ms"]
    return "\n".join([
        "# API 并发测试报告",
        "",
        f"- 测试时间：{generated_at}",
        f"- 测试目标：`{summary['target']}`",
        f"- API 地址：`{summary['base_url']}`",
        f"- 并发数：{summary['concurrency']}",
        f"- 请求数：{summary['requests']}",
        f"- 成功率：{summary['success_rate_percent']}%",
        f"- 吞吐量：{summary['throughput_requests_per_second']} 请求/秒",
        "",
        "| 平均耗时 | P50 | P95 | P99 | 最大耗时 |",
        "|---:|---:|---:|---:|---:|",
        f"| {latency['average']} ms | {latency['p50']} ms | {latency['p95']} ms | {latency['p99']} ms | {latency['maximum']} ms |",
        "",
        f"状态码统计：`{json.dumps(summary['status_counts'], ensure_ascii=False)}`",
        "",
        "> 本报告记录实测值，不预设性能结论。不同并发档位应在相同机器、相同数据库和相同模型配置下分别运行。",
        "",
    ])


async def async_main(args: argparse.Namespace) -> int:
    if args.requests < 1 or args.concurrency < 1:
        raise ValueError("--requests and --concurrency must be positive.")
    if args.concurrency > args.requests:
        args.concurrency = args.requests
    if args.target in {"repository", "assistant"} and (not args.owner or not args.name):
        raise ValueError(f"{args.target} target requires --owner and --name.")

    print(
        f"Running {args.requests} {args.target} requests with concurrency {args.concurrency} "
        f"against {args.base_url}"
    )
    results, elapsed = await run_load(args)
    summary = summarize(args, results, elapsed)
    generated_at = datetime.now().astimezone().isoformat(timespec="seconds")
    timestamp = datetime.now().astimezone().strftime("%Y%m%d-%H%M%S")
    args.output_dir.mkdir(parents=True, exist_ok=True)
    json_path = args.output_dir / f"load-{args.target}-{timestamp}.json"
    markdown_path = args.output_dir / f"load-{args.target}-{timestamp}.md"
    json_path.write_text(
        json.dumps({"generated_at": generated_at, "summary": summary, "results": results}, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    markdown_path.write_text(markdown_report(summary, generated_at), encoding="utf-8")
    print(json.dumps(summary, ensure_ascii=False, indent=2))
    print(f"Reports: {json_path} and {markdown_path}")
    return 0 if summary["failed"] == 0 else 1


def main() -> int:
    return asyncio.run(async_main(parse_args()))


if __name__ == "__main__":
    raise SystemExit(main())
