"""Auto-fix and pull request creation service.

Two-round fix generation:
  Round 1 — LLM searches the repo and outputs ONLY the bug location (file path).
  Round 2 — Code reads that file, sends it to LLM, LLM outputs the fix.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone

from app.assistant.harness import AgentHarness
from app.core.effective_config import get_effective_config
from app.services.github_client import GitHubClient, GitHubClientError
from app.services.repository_url import RepositoryRef
from app.storage import repository_store


@dataclass
class FixProposal:
    """The result of analysing a bug issue and generating a fix."""

    branch_name: str
    title: str
    pr_body: str
    files: list[FixFileChange] = field(default_factory=list)


@dataclass
class FixFileChange:
    """One file to create or update as part of a fix."""

    path: str
    content: str
    commit_message: str
    sha: str | None = None


@dataclass
class FixResult:
    """Result of attempting an auto-fix."""

    success: bool
    pr_url: str | None = None
    branch_name: str | None = None
    error: str | None = None
    files_changed: list[str] = field(default_factory=list)
    summary: str | None = None


class AutoFixService:
    """Analyse a bug issue and create a fix pull request."""

    def __init__(self) -> None:
        # 检查是否配置了 LLM API key，未配置则无法生成修复
        self._llm_available = bool(get_effective_config().llm_api_key)

    async def fix_issue(self, owner, name, issue_number, issue_title, issue_body, labels) -> FixResult:
        """Full auto-fix pipeline: locate → generate → branch → commit → PR."""
        if not self._llm_available:
            return FixResult(success=False, error="LLM is not configured")

        ref = RepositoryRef(owner=owner, name=name)
        suffix = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S%f")[:17]
        branch_name = f"auto-fix/issue-{issue_number}-{suffix}"

        try:
            fix_proposal = await self._generate_fix_with_harness(
                owner, name, issue_number, issue_title, issue_body, labels, branch_name,
            )
        except Exception as exc:
            return FixResult(success=False, branch_name=branch_name, error=str(exc))

        if fix_proposal is None or not fix_proposal.files:
            return FixResult(
                success=False, branch_name=branch_name,
                error=fix_proposal.pr_body if fix_proposal and fix_proposal.pr_body
                else "Could not generate fix code.",
            )

        # ── Step ③: Create branch ───────────────────────────────────
        try:
            async with GitHubClient() as gh:
                repo = await gh.get_repository(ref)
                default_branch = repo.get("default_branch") or "main"
                commits = await gh.get_commits(ref, 1)
                if not commits:
                    return FixResult(success=False, error="No commits found on default branch.")
                sha = commits[0]["sha"]
                await gh.create_branch(ref, branch_name, sha)

            async with GitHubClient() as gh:
                for change in fix_proposal.files:
                    await gh.create_or_update_file(
                        ref, change.path, change.content,
                        commit_message=change.commit_message,
                        branch=branch_name, sha=change.sha,
                    )

            async with GitHubClient() as gh:
                pr = await gh.create_pull_request(
                    ref,
                    title=fix_proposal.title or f"fix: {issue_title[:72]}",
                    head=branch_name,
                    base=default_branch,
                    body=f"Closes #{issue_number}\n\n{fix_proposal.pr_body}\n\n"
                         f"_🤖 Auto-generated by IssueScope_",
                )
        except GitHubClientError as exc:
            return FixResult(
                success=False, branch_name=branch_name,
                error=f"GitHub operation failed: {exc.message}",
                files_changed=[change.path for change in fix_proposal.files],
            )

        files_changed = [change.path for change in fix_proposal.files]
        return FixResult(
            success=True, pr_url=pr["html_url"], branch_name=branch_name,
            files_changed=files_changed, summary=fix_proposal.pr_body,
        )

    # ── Two-round fix generation ───────────────────────────────────

    async def _generate_fix_with_harness(self, owner, name, issue_number,
                                         issue_title, issue_body, labels, branch_name) -> FixProposal | None:
        """Round 1: locate buggy file.  Round 2: read and fix it."""
        snapshot = repository_store.get(owner, name)
        if snapshot is None:
            return FixProposal(branch_name=branch_name, title="", pr_body="Repository not synced yet.", files=[])

        ref = RepositoryRef(owner=owner, name=name)
        harness = AgentHarness()
        labels_str = ", ".join(labels) if labels else "(none)"
        body_str = issue_body or "(no body provided)"

        from app.services.memory_service import get_similar_fixes
        similar_fixes = await get_similar_fixes(owner, name, issue_title, issue_body)
        memory_text = ""
        if similar_fixes:
            memory_text = "\n\nPast fixes:\n" + "\n".join(
                f"- {item['title']}: {item['summary']}" for item in similar_fixes
            )

        # ── Round 1: locate ────────────────────────────────────────
        loc_messages = [
            {
                "role": "system",
                "content": (
                    "You are a bug locator. Use search_files to find the file "
                    "mentioned in the bug report. Then read it to find the bug. "
                    "Output ONLY this JSON:\n"
                    '{"file": "path/to/file.py", "line": 42, "description": "what is wrong"}\n'
                    f"Repository: {snapshot.identity.full_name}\n"
                    f"{memory_text}\n"
                ),
            },
            {
                "role": "user",
                "content": (
                    f"Bug: {issue_title}\n{body_str}\nLabels: {labels_str}\n\n"
                    "Find the file and the buggy line. Output the JSON."
                ),
            },
        ]

        loc_text, _ = await harness.run(loc_messages, snapshot)
        target_file = None
        target_line = None

        # Parse the file path from round 1.
        if loc_text:
            loc_json = re.search(r'\{[^}]*"file"[^}]*\}', loc_text, re.DOTALL)
            if loc_json:
                try:
                    loc_data = json.loads(loc_json.group())
                    target_file = loc_data.get("file", "").strip()
                    target_line = loc_data.get("line")
                except (json.JSONDecodeError, AttributeError):
                    pass

        if not target_file:
            # Fallback: search for the file name from bug title.
            import re as _re
            words = _re.findall(r'[\w./]+\.\w+', issue_title)
            if words:
                target_file = words[0]

        if not target_file:
            return FixProposal(
                branch_name=branch_name, title="",
                pr_body="Could not locate the buggy file. Make sure the bug report mentions a file path.",
                files=[],
            )

        # ── Round 2: read + fix ────────────────────────────────────
        file_content = None
        async with GitHubClient() as gh:
            try:
                content, _ = await gh.get_file_content(
                    ref, target_file, snapshot.identity.default_branch, 50000,
                )
                if content:
                    file_content = content
                    # Get SHA for the file.
                    from urllib.parse import quote
                    encoded = quote(target_file, safe="/")
                    try:
                        meta = await gh._get(
                            f"/repos/{ref.owner}/{ref.name}/contents/{encoded}",
                            params={"ref": snapshot.identity.default_branch},
                        )
                        file_sha = meta.get("sha")
                    except Exception:
                        file_sha = None
            except Exception:
                return FixProposal(
                    branch_name=branch_name, title="",
                    pr_body=f"Could not read file: {target_file}",
                    files=[],
                )

        if not file_content:
            return FixProposal(
                branch_name=branch_name, title="",
                pr_body=f"File {target_file} is empty or binary.",
                files=[],
            )

        fix_messages = [
            {
                "role": "system",
                "content": (
                    f"The bug is in {target_file} (line ~{target_line or 'unknown'}). "
                    "Fix the bug. Output ONLY this JSON:\n"
                    '```json\n'
                    '{"title": "fix: short", "pr_body": "one sentence", '
                    '"files": [{"path": "FILE_PATH", "content": "FULL_FILE_CONTENT", '
                    '"commit_message": "fix: what changed"}]}\n'
                    '```\n'
                    "CRITICAL: 'path' must be the exact path. "
                    "Include the FULL file content after the fix. "
                    "Do not create new files."
                ),
            },
            {
                "role": "user",
                "content": (
                    f"## Bug Report\n{issue_title}\n{body_str}\n\n"
                    f"## File: {target_file}\n```\n{file_content}\n```\n\n"
                    f"Line ~{target_line or 'unknown'} has the bug. Fix it. Output JSON."
                ),
            },
        ]

        final_text, _ = await harness.run(fix_messages, snapshot)
        if not final_text:
            return None

        # Parse JSON from round 2.
        json_match = re.search(r'```json\s*(\{.*?\})\s*```', final_text, re.DOTALL)
        if not json_match:
            json_match = re.search(r'(\{.*?"files"\s*:.*?\})', final_text, re.DOTALL)
        if not json_match:
            fix_messages.append({"role": "user", "content": "Output ONLY valid JSON."})
            final_text, _ = await harness.run(fix_messages, snapshot)
            if final_text:
                json_match = re.search(r'```json\s*(\{.*?\})\s*```', final_text, re.DOTALL)
                if not json_match:
                    json_match = re.search(r'(\{.*?"files"\s*:.*?\})', final_text, re.DOTALL)

        if not json_match:
            return FixProposal(branch_name=branch_name, title="", pr_body="Could not parse fix JSON.", files=[])

        try:
            data = json.loads(json_match.group(1))
        except json.JSONDecodeError:
            return FixProposal(branch_name=branch_name, title="", pr_body="Failed to parse JSON.", files=[])

        files_raw = data.get("files", [])
        if not files_raw:
            return FixProposal(branch_name=branch_name, title=data.get("title", ""), pr_body=data.get("pr_body", ""), files=[])

        # Resolve SHA and build FixProposal.
        async with GitHubClient() as gh:
            files: list[FixFileChange] = []
            for f in files_raw:
                path = f.get("path", target_file)
                content = f.get("content", "")
                commit_msg = f.get("commit_message", f"fix: {issue_title[:60]}")
                sha = None
                try:
                    meta = await gh._get(
                        f"/repos/{ref.owner}/{ref.name}/contents/{quote(path, safe='/')}",
                        params={"ref": snapshot.identity.default_branch},
                    )
                    sha = meta.get("sha")
                except Exception:
                    pass
                files.append(FixFileChange(path=path, content=content, commit_message=commit_msg, sha=sha))

        return FixProposal(
            branch_name=branch_name,
            title=data.get("title", f"fix: {issue_title[:72]}"),
            pr_body=data.get("pr_body", issue_title),
            files=files,
        )
